"""Add source column to DocumentSummary table

Revision ID: d02dda149530
Revises: fd1c410f9841
Create Date: 2025-08-04 08:28:54.487481+00:00

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d02dda149530"
down_revision = "fd1c410f9841"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("document_summaries", schema=None) as batch_op:
        batch_op.add_column(sa.Column("source", sa.String(length=50), nullable=True))

    connection = op.get_bind()
    connection.execute(sa.text("UPDATE document_summaries SET source = 'default' WHERE source IS NULL"))

    batch_op.alter_column('required_field', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("document_summaries", schema=None) as batch_op:
        batch_op.drop_column("source")

    # ### end Alembic commands ###
