"""Initial schema

Revision ID: 69225136cbe8
Revises: 
Create Date: 2025-07-21 05:08:51.179519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69225136cbe8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'documents', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'documents', type_='unique')
    # ### end Alembic commands ###