name: Build Base Image

on:
  push:
    branches:
      - main
    paths:
      - 'requirements-azure.txt'
      - 'base.Dockerfile' # Assuming you are using the multi-stage build

jobs:
  build-and-push-base:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: 'Login to Azure Container Registry'
        uses: azure/docker-login@v1
        with:
          login-server: gianidevacr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: 'Build and push base image'
        run: |
          docker build -t gianidevacr.azurecr.io/giani-ai-base:latest -f base.Dockerfile .
          docker push gianidevacr.azurecr.io/giani-ai-base:latest
