name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  # Job 1: Build the base image (only if needed)
  build-base-image:
    # This job only runs if the push
    # includes changes to the requirements file or the base Dockerfile.
    if: "contains(github.event.head_commit.message, '[build base]') || contains(join(github.event.commits.*.modified), 'requirements-azure.txt') || contains(join(github.event.commits.*.modified), 'base.Dockerfile')"

    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: 'Login to Azure Container Registry'
        uses: azure/docker-login@v1
        with:
          login-server: gianidevacr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: 'Build and push base image'
        run: |
          echo "Dependency change detected. Building and pushing new base image..."
          docker build -t gianidevacr.azurecr.io/giani-ai-base:latest -f base.Dockerfile .
          docker push gianidevacr.azurecr.io/giani-ai-base:latest

  # Job 2: Build and deploy the application
  deploy-application:
    needs: build-base-image

    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Login to Azure Container Registry'
        uses: azure/docker-login@v1
        with:
          login-server: gianidevacr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: 'Set Version Tag'
        id: set_version
        run: echo "tag=${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: 'Build and push application image'
        run: |
          docker build -t gianidevacr.azurecr.io/giani-ai:${{ steps.set_version.outputs.tag }} .
          docker tag gianidevacr.azurecr.io/giani-ai:${{ steps.set_version.outputs.tag }} gianidevacr.azurecr.io/giani-ai:latest

          docker push gianidevacr.azurecr.io/giani-ai:${{ steps.set_version.outputs.tag }}
          docker push gianidevacr.azurecr.io/giani-ai:latest

      - name: 'Deploy to App Service'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'giani-dev-wa'
          images: 'gianidevacr.azurecr.io/giani-ai:${{ steps.set_version.outputs.tag }}'

